<main-menu-component
    smartphone-link="{{asset('search?filterByCategory[]=smartphone')}}"
    tvs-link="{{asset('search?filterByCategory[]=tv')}}"
    notebooks-link="{{asset('search?filterByCategory[]=notebook')}}"
    tablets-link="{{asset('search?filterByCategory[]=tablet')}}"
    roteadores-link="{{asset('search?filterByCategory[]=roteador')}}"
    hds-link="{{asset('search?filterByCategory[]=hd')}}"
    processador-link="{{asset('search?filterByCategory[]=processador')}}"
    papelaria-link="{{asset('search?filterByCategory[]=papelaria')}}"
    sonorizacao-link="{{asset('search?filterByCategory[]=sonorizacao')}}"
    galeria="{{$gallery}}"
>
</main-menu-component>